id: P007993
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:53:52.649672
source_metadata:
  id: bdr:W2PD19983
  title: 'ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ། '
  author: ''
  volumes:
    bc7c96cb12fd40d7a66fc5ece5b0038f:
      image_group_id: I2PD19995
      title: Volume 1 of zab chos zhi khro dgongs pa rang grol/
      volume_number: 1
      total_pages: 336
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
