id: P007993
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19983
  title: 'ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ། '
  author: ''
  volumes:
    feedc6180b624b71b62202fde88ce59d:
      image_group_id: I2PD19995
      title: ''
      volume_number: 1
      total_pages: 336
ebook_metadata:
  title: 'ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ། '
  author: ''
  sku: P007993
  cover: cover.jpg
  layers:
  - pagination
